docs/psoc6/quickref.rst

Added initial documentation for the `machine` module and `machine.Pin` class.
Rendered here: https://ifx-micropython.readthedocs.io/en/ports-psoc6_machine_pin/

docs/psoc6:added initial docs for psoc6 modmachine and machine.Pin

---

.github/workflows/ports_psoc6.yml

v2 using deprecated node.js version

.github/ports_psoc6.yml: Updated checkout action to v3.

---

ports/psoc6/main.c
ports/psoc6/modules/network/network_ifx_whd.c
ports/psoc6/modules/network/network_ifx_whd.h

I have already taken the changes contributed to network modules and added scan function and init related part. All works for me now.
**Few points to note:**
1. Our stack has lot more breakdown on security type while mpy conventions ask to classify them to 5:
There are five values for security:
0 – open
1 – WEP
2 – WPA-PSK
3 – WPA2-PSK
4 – WPA/WPA2-PSK
But this is not enough for certain types like "WPA3..." or "UNKNOWN" types. And hence, I had to end up extending the mpy convention to more values. This should be taken care while we document it.
2. network_ifx_whd_print() has to be later fixed by rendering right status information. Currently, it does not block our progress and has low priority. Ticket for the same is in backlog.

ports/psoc6 : Fixed scan function in network module.

---

ports/psoc6/Makefile
ports/psoc6/drivers/machine/psoc6_pwm.c
ports/psoc6/drivers/machine/psoc6_pwm.h
ports/psoc6/modules/machine/machine_pwm.c
ports/psoc6/modules/machine/modmachine.c
ports/psoc6/modules/machine/modmachine.h
ports/psoc6/mpconfigport.h
tests/psoc6/pwm.py
tests/psoc6/pwm.py.exp

Description
There is an existing extmod for PWM & it demands the implementation of certain functions in the port. Corresponding macros are enabled & required functions are implemented. cy_hal is used & since it's not having the functions to return the current duty cycle, frequency or pulse width then standard formulas are used to calculate the current values in corresponding functions & variables are used to store them.

PWM module implementation. 

---

.github/workflows/ports_psoc6.yml
docs/psoc6/installation.rst
ports/psoc6/boards/CY8CPROTO-062-4343W/makefile_mtb.mk
tools/psoc6/mpy-psoc6.cmd
tools/psoc6/mpy-psoc6.sh

Description
* Added command to erase external flash.
* Added the openocd bsp configuration to flashing process. This could resolve the issues with new boards. If that is the case, we can delete the stage of flashing the hello-world. But first needs testing.

Ext flash erase

---

tools/psoc6/mpy-psoc6.cmd
tools/psoc6/mpy-psoc6.sh

Openocd uploaded to release section.

tools/psoc6/mpy-psoc6: Added openocd from self releases.

---

docs/psoc6/quickref.rst
ports/psoc6/modules/network/network_ifx_wcm.c
tests/psoc6/multi/network.py
tests/psoc6/multi/network.py.exp
tests/psoc6/multi/network_config.py
tests/psoc6/multi/network_config.py.exp

* Refactor into get_ap_conf, get_sta_conf set_sta_conf, and set_ap_conf. Should improve maintenance.
* Documentation is missing, but will follow the completion of the whole network class.
* TxPower, hidden and power management not implemented as in reference network API. Secondary features not exposed in the main wcm api.
* Reworked ifconfig(), and added corresponding tests.
* Complement module instance print() function.

network.config()

---

ports/psoc6/modules/machine/machine_adc.c
ports/psoc6/modules/machine/machine_adc.h
ports/psoc6/modules/machine/machine_adcblock.c
ports/psoc6/modules/machine/machine_adcblock.h

ports/psoc6/modules/machine/machine_adc: WIP refactor relationship.

---

docs/psoc6/quickref.rst

Description
Fixed documentation where rendering did not work right.

docs/psoc6: Fixing code alignment and text.

---

docs/psoc6/quickref.rst
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/modmachine.c

Description
- Enables Signal module and available functions work.
- Ideally, I would have wanted to reuse the APIs in driver but hal apis were more promising.
- The tests/extmod/machine_signal.py should be passed but there are two problems:
1. It depends on machine.PinBase which is another extmod extended by MPY but needs to enabled in our port.
2. The value() is not used as it is mentioned [here](https://ifx-micropython.readthedocs.io/en/latest/library/machine.Pin.html#machine-pin). The guide says value() returns undefined value which is how …

ports/psoc6: Adding code for machine.Signal functionality.

---

ports/psoc6/mtb-libs/makefile_mtb.mk
tools/psoc6/mpy-psoc6.cmd
tools/psoc6/mpy-psoc6.sh

* Added .cfg selection for openocd program command based on BOARD bsp in makefile.
* Added new board in installation scripts, including selection of .cfg file depending on board.

Multi bsp program

---

ports/psoc6/Makefile
ports/psoc6/boards/make-pins.py
ports/psoc6/psoc6_prefix.c
tools/codeformat.py

**Description**
At this point, the script make-pins.py is triggered and running successfully as part of "make" command. There are couple of things that require refactoring especially in Makefile but this can be addressed as I finish with DESMAKERS-3536. Consider this as first-level PR to be informed on changes. In nutshell, the script will automatically:
- Extract pins for cpu and make intermediate files.
- Generate pins.h, pins_<BOARD_NAME>.c and pins_qstr.h which are all required micropython objects for pins.

Scripted pin gen

---

ports/psoc6/Makefile
ports/psoc6/boards/CY8CPROTO-062-4343W/mpconfigboard.mk
ports/psoc6/boards/CY8CPROTO-063-BLE/mpconfigboard.mk
ports/psoc6/boards/make-pins-csv.py
ports/psoc6/boards/make-pins.py
ports/psoc6/modules/machine/machine_adcblock.c
ports/psoc6/modules/machine/pins.c
ports/psoc6/modules/machine/pins.h

Description
With this PR, automatic pin generation works fine. I have the following changes there:
- Python scripts that handle the automatic generation of csv and headers in build (make-pins-csv and make-pins)
- Makefile changes to integrate the sources with the rest
- The changes in machine_adcblock has to be so for now until we extend machine_pin structure to incorporate alternate functions

ports/psoc6: Completing make_pins changes.

---

docs/psoc6/quickref.rst

Description
Fix Typo in the frequency in I2C documentation

ports/psoc6: Fix i2c Documentation.

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
ports/psoc6/main.c
ports/psoc6/modules/machine/machine_adc.h
ports/psoc6/modules/machine/machine_adcblock.h
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/machine_pin.h
ports/psoc6/modules/machine/machine_spi.c
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/spi_hard.py

To be reviewed after #97. 
Added deinit functions and refactoring for pin_phy changes.

Machine spi deinit

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
ports/psoc6/main.c
ports/psoc6/modules/machine/machine_adc.h
ports/psoc6/modules/machine/machine_adcblock.h
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/machine_pin.h
ports/psoc6/modules/machine/machine_pwm.c
ports/psoc6/modules/machine/machine_spi.c
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/spi_hard.py

ports/psoc6/../machine_pwm.c: Added deinit and pin phy refactor.

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
extmod/machine_i2c.c
extmod/machine_i2c.h
ports/psoc6/main.c
ports/psoc6/modules/machine/machine_adc.h
ports/psoc6/modules/machine/machine_adcblock.h
ports/psoc6/modules/machine/machine_i2c.c
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/machine_pin.h
ports/psoc6/modules/machine/machine_pin_phy.h
ports/psoc6/modules/machine/machine_pwm.c
ports/psoc6/modules/machine/machine_spi.c
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/spi_hard.py

To be reviewed after #95.
Added deinitialization function to i2c module. This is directly added to the extmod.
Docs amendments will be done after the complete machine module is refactored for the pin_phy.

Machine i2c deinit

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
extmod/machine_i2c.c
extmod/machine_i2c.h
ports/psoc6/main.c
ports/psoc6/modules/machine/machine_adc.c
ports/psoc6/modules/machine/machine_adc.h
ports/psoc6/modules/machine/machine_adcblock.c
ports/psoc6/modules/machine/machine_adcblock.h
ports/psoc6/modules/machine/machine_i2c.c
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/machine_pin.h
ports/psoc6/modules/machine/machine_pin_phy.c
ports/psoc6/modules/machine/machine_pin_phy.h
ports/psoc6/modules/machine/machine_pwm.c
ports/psoc6/modules/machine/machine_spi.c
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/spi_hard.py

This PR will change the destination branch after #94 is merged. Please, review the other one first.
Description
* Adding obj deinit and module deinit to machine.Pin.
* Adding obj deinit and module deinit to machine.ADC and machine.ADCBlock. Additional cleanup refactoring to accommodate pin_phy and scope of each friend classes.

ports/psoc6: Adding deinit to pin and adc machine classes.

---

docs/psoc6/installation.rst
docs/psoc6/quickref.rst
tools/psoc6/mpy-psoc6.py

* Added python mpy-psoc6.py utility script replacing native options
* Added kitprog update option to device-setup
* Coloring output success, errors and user interaction requests
* Extended command help
* Handling error message from fw-loader and openocd (usually happening when the boards are not connected)
* Updated installation documentation --> https://ifx-micropython.readthedocs.io/en/add-kitprog-check-install-script/psoc6/installation.html

New python mpy-psoc6 script and  kitprog check install option

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/mpconfigport.h
ports/psoc6/mphalport.c
tests/psoc6/dut/pin.py
tests/psoc6/dut/pin.py.exp
tests/psoc6/timer.py
tests/psoc6/timer.py.exp

Description
1. Implementation of Pin.irq() function
2. Non- Blocking UART  
3. Fix for scheduler
4. Documentation
With these modifications. GPIO interrupt & periodic timer is now working.
**Known issues**: In case of a GPIO interrupt,  after the execution of a print statement inside the callback function( if exists), need to press the Enter key to enter back into REPL.  
since the same case works perfectly in the case of Timer, need to evaluate that in more depth.

Fix of scheduler & Machine class interrupt function implementation

---

.github/workflows/ports_psoc6.yml
ports/psoc6/boards/CY8CPROTO-062-4343W/mpconfigboard.h
ports/psoc6/modules/psoc6/psoc6_qspi_flash.c
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/run_psoc6_tests.sh

**Description**:
Provides fix for large file transfer issue as raised by the community user.
**Issues**: 
- The write blocks enabled for the port were not correctly configured to handle larger data.
- Atomic sections were not enabled and hence not allowing the FS operations to run without any other system interrupts.
**Resolution**:
- Enabled atomic sections
- Refactored psoc6 qspi flash API.
- Moved flash configurations from src files to board config.
- Enabled micropython offered tests and the corresponding changes to run them in our CI/CD …

Fix mem issue

---

docs/psoc6/installation.rst
docs/psoc6/intro.rst

docs/psoc6: Minor fixes in installation docs.

---

.github/workflows/ports_psoc6.yml
tests/psoc6/flash.py
tests/psoc6/run_psoc6_tests.sh
tests/psoc6/timer.py
tests/psoc6/timer.py.exp
tools/psoc6/get-devs.py

To be reviewed after #118: 
* Allowing the ports_psoc6.yml to run on error.
* Skipping failing tests which require module fixing or refactor
* Fix parsing Kitprog devices attribute matching. Changed after debugger firmware update. 
* Exit properly on error for run_psoc6_tests.sh

Test script exit on error

---

ports/psoc6/machine_timer.c
tests/psoc6/timer.py
tests/psoc6/timer.py.exp
tools/codeformat.py

Description
Timer Module Fix with tests

Machine timer

---

ports/psoc6/machine_rtc.c
ports/psoc6/main.c
tests/psoc6/rtc.py
tests/psoc6/rtc.py.exp
tests/psoc6/rtc_memory_write_check.py

@NikhitaR-IFX here are the changes.
* Moved the rtc_init.c to soft_reset:  in main.c (The only real necessary change).
* Unified alarm setup, which is now called within alarm() and if repeat in the internal irq. 
* irq() is only setting the callback
* Replaced sleep() in test for condition check with timeout in tests (this would be less sensitive to time fluctuation and minimize that waiting time).
* Added __ del __() (** this might be removed again).
Things that are still missing:
1. consider cyhal_init()/free() to be delegated to the main(), …

Rtc tests refactor

---

.github/workflows/stale_issues.yml

Adding a workflow reference to the reusable workflow at:
https://github.com/Infineon/workflows/blob/master/.github/workflows/epe_stale_issues.yml
To automatically handle and close stale issues.

add workflow to automatically close stale issues

---

ports/psoc6/boards/CY8CKIT-062S2-AI/manifest.py
ports/psoc6/boards/CY8CPROTO-062-4343W/manifest.py
ports/psoc6/boards/CY8CPROTO-063-BLE/manifest.py
ports/psoc6/mbedtls/mbedtls_config.h

Fixed access to HTTPS links and thereby mip is working. 
connect the board to the network and try installing using mip
import mip
mip.install('neopixel')
mip. install("https://raw.githubusercontent.com/jaenrig-ifx/micropython-lib/mpy-lib/pasco2-sensor-module/micropython/drivers/sensor/pasco2/pasco2.py")
or anything else. I hope this works on your end also!

ports/psoc6: Https fix.

---

tests/ports/psoc6/run_psoc6_tests.sh
tests/ports/psoc6/test_scripts/fs.py
tests/ports/psoc6/test_scripts/fs_adv.py.exp
tests/ports/psoc6/test_scripts/fs_adv_sd.py.exp
tests/ports/psoc6/test_scripts/fs_basic.py.exp
tests/ports/psoc6/test_scripts/fs_basic_sd.py.exp

New fs tests does not check on output of cp commands, but it does the following:
- Set the list of files to copy to the device memory based on "basic" or "adv" (advance) tests
- Check if those files already exist on the device by listing the specific path: (fs ls command)
- Remove the files if they already exists (rm command)
- Copy the files (cp command)
- Check if the files have been properly copied (fs command)

tests/ports/psoc6/fs: Refactor fs large ffile script.

---

ports/psoc6/boards/CY8CKIT-062S2-AI/mpconfigboard.h
ports/psoc6/boards/CY8CPROTO-062-4343W/mpconfigboard.h
ports/psoc6/boards/CY8CPROTO-063-BLE/mpconfigboard.h
ports/psoc6/machine_i2c.c
ports/psoc6/machine_i2s.c
ports/psoc6/machine_pwm.c
ports/psoc6/machine_spi.c

- Moved Machine object configs to board-specific files
- Limited the Max of machine objects for each machine class to the actual ones available in that board.

Fix machine obj instances

---

docs/psoc6/installation.rst
tools/psoc6/mpy-psoc6.py

* Implemented print flush
* Added serial adapter serial number passing option (select device when multiple devices are connected)
* Kitprog3 fw update not enabled by default
* Suggestion of fw update when openocd fails
Download this one to try it out:
https://github.com/Infineon/micropython/blob/mpy-psoc6-v0.4/tools/psoc6/mpy-psoc6.py

Mpy psoc6 v0.4

---

ports/psoc6/psoc6_flash.c
ports/psoc6/psoc6_qspi_flash.c

Fix external flash fat fs

---

docs/psoc6/quickref.rst
ports/psoc6/machine_pin.c

* Exception for incompatible pull-init value configurations on input
* Handling of consistency between pull-resistors and initial values 
I have checked manually with the logic analyzer all these configurations:
```
from machine import Pin
pin = Pin('P9_4', mode=Pin.OUT, value=1)
```
Not added to ci/cd tests as continues init()/deinit(), and hardware configurations for different pins requires a thorough check for compatible configurations.

ports/psoc6/machine_pin.c: Validation of pull resistors + value config.

---

docs/psoc6/mpy-usage.rst
ports/psoc6/main.c
tests/ports/psoc6/run_psoc6_tests.sh

Implemented safe boot mode during reset. This allows user to bypass the execution of main.py and boot.py 
Only manual test: Add main.py with infinite loop with some print statement, reset and see the print output. Enter into safe mode by pressing both reset and user button on board. release user button after the LED blinks twice. Now the main.py is not executed and can be accessed with file system and modified.

Exit blocking main loop

---

.github/workflows/stale_issues.yml
.github/workflows/synch_upstream.yml
README.md

Removal of _**ports-psoc6-ifx**_ branch as it does not really serve the purpose of having a _**ports-psoc6-main**_ from which we can rise a PR.

ports/psoc6: PSoC6 Infineon fork patch.

---

docs/conf.py

https://ifx-micropython.readthedocs.io/en/fix-doc-build/index.html

docs/conf.py: Removed get_html_theme_path for rtd conf.

---

tests/ports/psoc6/board_only_hw/multi/network.py
tests/ports/psoc6/board_only_hw/multi/network_config.py
tests/ports/psoc6/board_only_hw/single/timer.py
tests/ports/psoc6/mp_custom/fs.py

* Changes in line ending of mpremote made the fs tests fail --> Fixed now (and added some debug logger traces.)
* Timer test and module is behind failure of the subsequent test --> Added workaround with time.sleep
* Randomize ssid and channels to reduce connection issues in tests.

Fix large storage and 063-BLE timer workaround

---

docs/psoc6/quickref.rst
ports/psoc6/machine_i2s.c
ports/psoc6/modmachine.c
ports/psoc6/modmachine.h
ports/psoc6/mpconfigport.h
tests/ports/psoc6/board_ext_hw/multi/i2s_rx.py
tests/ports/psoc6/board_ext_hw/multi/i2s_rx.py.exp
tests/ports/psoc6/board_ext_hw/multi/i2s_tx.py

- machine.freq() implementation for setting clock by the user
- Remove clock init from I2S and modified tests
- Documentation

Clock feature

---

docs/psoc6/quickref.rst

- Added warning - Supported only for psoc6 port.
- Added clock details in PDM section

docs/psoc6/quickref.rst: Fix clock details in PDM section.

---

tests/ports/psoc6/board_ext_hw/multi/i2s_rx.py
tests/ports/psoc6/board_ext_hw/single/adc.py
tests/ports/psoc6/board_ext_hw/single/i2c.py
tests/ports/psoc6/board_ext_hw/single/pwm.py
tools/psoc6/get-devs.py
tools/psoc6/wsl-usb.py

Ruff fixes
