tools/ci.sh

Signed-off-by: jaenrig-ifx <enriquezgarcia.external@infineon.com>

tools/ci.sh: Updated docker image and build func for PSoC6.

---

tests/run-tests.py

Signed-off-by: jaenrig-ifx <enriquezgarcia.external@infineon.com>

tests/run-tests.py: Added --write-exp-on-target option.

---

ports/psoc6/drivers/machine/psoc6_gpio.c
ports/psoc6/modules/machine/machine_pin.c
ports/psoc6/modules/machine/pins.c
ports/psoc6/modules/machine/pins.h

Bugfixes discovered during softI2C implementation. 
This merge is crucial for the merge of the I2C implementation later.

Bugfixes on machine.Pin

---

docs/psoc6/quickref.rst

Fixes to the docu. 
Machine.Pin and Machine.I2C sections

docs/psoc6:fixes in docu

---

ports/psoc6/mpconfigport.h
tests/psoc6/README

Incorporating changes in port config to enable relevant tests that were skipped before. Parallelly, test completion status monitoring is updated.

Ports psoc6 tests enablement

---

ports/psoc6/Makefile
ports/psoc6/drivers/machine/psoc6_pwm.c
ports/psoc6/drivers/machine/psoc6_pwm.h
ports/psoc6/modules/machine/machine_pwm.c
ports/psoc6/modules/machine/modmachine.c
ports/psoc6/modules/machine/modmachine.h
ports/psoc6/mpconfigport.h
tests/psoc6/pwm.py
tests/psoc6/pwm.py.exp

Description
Reopening pull request to fix the author contribution fail

Machine pwm

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
ports/psoc6/Makefile
ports/psoc6/modules/machine/machine_pwm.c

PWM module documentation

---

ports/psoc6/modules/network/network_ifx_wcm.c
ports/psoc6/modules/network/network_ifx_wcm.h
tests/psoc6/multi/network.py
tests/psoc6/multi/network.py.exp

Description
- network.scan() refactor (missing timer timeout to avoid blocking waiting for result)
- network.status() completed. Not implemented link status, as not clearly available for our api -> redirect in docs user to active() -> connected vs not connected.
- more verbose network multi test.

Network module progress

---

docs/psoc6/feature_list.rst
docs/psoc6/quickref.rst
ports/nrf/modules/os/microbitfs.c
ports/nrf/modules/os/modos.c
ports/psoc6/Makefile
ports/psoc6/modules/machine/machine_spi.c
ports/psoc6/modules/machine/modmachine.c
ports/psoc6/modules/machine/modmachine.h
ports/psoc6/mpconfigport.h
ports/psoc6/mphalport.c
ports/psoc6/mphalport.h
tests/psoc6/multi/network.py
tests/psoc6/pwm.py
tests/psoc6/spi_hard.py
tests/psoc6/spi_hard.py.exp
tests/psoc6/spi_soft.py
tests/psoc6/spi_soft.py.exp

Description
SPI Module implementation, tests & Documentation.
NB: Only Master mode is implemented

Ports psoc6 spi

---

ports/psoc6/modules/network/network_ifx_wcm.c
ports/psoc6/modules/network/network_ifx_wcm.h
tests/psoc6/multi/network.py
tests/psoc6/multi/network.py.exp

* Clean-up security support function
* Completed connect() function

Network ap connect()

---

tools/psoc6/wsl-usb.py

Description
Utility script for attaching usb devices in wsl within ifx network.

tools/psoc6/wsl-usb.py: Added utility for WSL USB device handling.

---

docs/psoc6/installation.rst
docs/psoc6/intro.rst
tools/psoc6/mpy-psoc6.cmd
tools/psoc6/mpy-psoc6.sh

Description
New factory acquire boards cannot be flashed with the installation script. While the root cause is found, first a hello-world.hex is flashed, and that allows proper flashing of the micropython firmware.

Install bug workaround

---

tools/psoc6/mpy-psoc6.cmd
tools/psoc6/mpy-psoc6.sh

tools/psoc6/mpy-psoc6: Updated with latest Arduino Lab IDE version.

---

docs/psoc6/installation.rst

Description
Fix help command for windows

 docs: Fix help command for psoc6.

---

ports/psoc6/mphalport.c
ports/psoc6/mphalport.h

Updates for fix build upstream

Fix build issue

---

ports/nrf/modules/os/microbitfs.c
ports/psoc6/machine_pin.c
tests/psoc6/dut/pin.py
tests/psoc6/dut/pin.py.exp

Increase coverage to all features implemented and per pin object callback.

Pin test ext cov

---

docs/psoc6/quickref.rst
tests/psoc6/dut/signal.py
tests/psoc6/dut/signal.py.exp

To be reviewed after #112!
Added extended machine signal system testing.

Signal test ext cov

---

docs/psoc6/installation.rst
docs/psoc6/quickref.rst
tools/psoc6/mpy-psoc6.py

Docs and installation script fixes.

Quick release fix

---

ports/psoc6/Makefile
ports/psoc6/mtb-libs/Makefile
ports/psoc6/mtb-libs/makefile_mtb.mk

Description
* Improved .c pin related files generation to avoid rebuild without changes.
* Rework board selection to avoid unstaged changes when building for other boards in mtb-libs/Makefile
* Renaming and makefile cleanup

No rebuild and dirty release fixes

---

docs/psoc6/quickref.rst
ports/psoc6/machine_pwm.c
tests/psoc6/dut/pwm.py
tests/psoc6/dut/pwm.py.exp
tests/psoc6/pwm.py
tests/psoc6/pwm.py.exp

Description
- Fixed calculations in PWM duty_u16 --> get and set functions
- Set duty_ns using pwm_duty_set_ns()
- Implemented DUT tests for PWM
- Removed invert functionality as this is currently not working and enabling this requires more efforts which challenges the current implementation of the module.
Related Issue
[DESMAKERS-3621](https://jirard.intra.infineon.com/browse/DESMAKERS-3621)

Bugfix pwm

---

.github/workflows/ports_psoc6.yml
docs/psoc6/quickref.rst
ports/psoc6/machine_wdt.c
ports/psoc6/main.c
ports/psoc6/modmachine.c
ports/psoc6/modmachine.h
ports/psoc6/mpconfigport.h
tests/psoc6/hw_ext/pwm.py
tests/psoc6/run_psoc6_tests.sh
tests/psoc6/wdt.py
tests/psoc6/wdt.py.exp
tests/psoc6/wdt_reset_check.py
tests/psoc6/wdt_reset_check.py.exp

Description
Added watchdog timer (WDT) machine module for psoc6 port.
functions implemented:
- Constructor
- feed()

Machine wdt

---

docs/psoc6/quickref.rst
ports/psoc6/machine_i2s.c
ports/psoc6/machine_pin_phy.h
tests/psoc6/hw_ext/multi_blocking/i2s_rx.py.exp

Description
* Allocation of physical pins for future machine gpio resource allocation/release.
* Reworked clock init to notify impact in the overall system. 
* Added "id" arg in I2S constructor ignored.

I2s pin phy and clock init

---

.github/workflows/ports_psoc6.yml
ports/psoc6/boards/CY8CKIT-062S2-AI/manifest.py
ports/psoc6/boards/CY8CKIT-062S2-AI/mpconfigboard.h
ports/psoc6/boards/CY8CKIT-062S2-AI/mpconfigboard.mk
ports/psoc6/boards/CY8CPROTO-063-BLE/mpconfigboard.mk
ports/psoc6/mtb-libs/makefile_mtb.mk

Description
* Added CY8KIT-062S2-AI board
* New board building and added to GA workflow builds

Ai kit build

---

tests/psoc6/bitstream/bitstream_rx.py
tests/psoc6/bitstream/bitstream_tx.py
tests/psoc6/hw_ext/adc.py
tests/psoc6/hw_ext/i2c.py
tests/psoc6/hw_ext/i2c.py.exp
tests/psoc6/hw_ext/multi_blocking/i2s_rx.py
tests/psoc6/hw_ext/multi_blocking/i2s_tx.py
tests/psoc6/hw_ext/pin.py
tests/psoc6/hw_ext/pwm.py
tests/psoc6/hw_ext/signal.py

Description
* To be reviewed after #138 
* Added pins for CY8CKIT-062S2-AI port tests

Ai kit eval test

---

tools/psoc6/mpy-psoc6.py

Description
Enabled AI Kit in flasher script to allow flashing.
**Test**: Generated locally .hex and hardcoded in the script the path to test and works fine.
*This is a draft and urls will be tested once the binary is generated and available as part release.

tools/psoc6/mpy-psoc6.py: Adding AI kit.

---

docs/psoc6/intro.rst
docs/psoc6/quickref.rst

- Removed pin listings from quickref.rst. For ADC, for now the channel to pin mapping table is removed as anyways it covered only  proto board. @ederjc : Please comment if you agree to have channels for ADC also mentioned in respective pinout diagrams instead.
- Updated example code for led to abstract the activeness of on-board led. Same changes have been made in hackster article as well here: https://www.hackster.io/Infineon_Team/micropython-on-psoc-fcf1d0

Pre v1 docs update

---

docs/psoc6/quickref.rst
ports/psoc6/boards/CY8CKIT-062S2-AI/mpconfigboard.h
ports/psoc6/boards/CY8CPROTO-062-4343W/mpconfigboard.h
ports/psoc6/boards/CY8CPROTO-063-BLE/mpconfigboard.h
ports/psoc6/machine_timer.c
ports/psoc6/modmachine.c
tests/ports/psoc6/timer.py
tests/ports/psoc6/timer.py.exp

- Refactored timer module to:
- Accept  timer id arg.
- Removed init as same functionality is supported through constructor.
- Added module deinit functions
- Allow multiple timer instance creation and storing to array.
- Updated docs to comply with changes in timer module
- Added test case showing usage of multiple timers.

Timer refactor

---

ports/psoc6/boards/CY8CKIT-062S2-AI/manifest.py
ports/psoc6/boards/CY8CPROTO-062-4343W/manifest.py
ports/psoc6/boards/CY8CPROTO-063-BLE/manifest.py

ports/psoc6: Remove neopixel.

---

docs/psoc6/installation.rst
tools/psoc6/mpy-psoc6.py

⚠️  Another PR for the install script is coming. We can test it functionally when all the changes are there. It is enough for this one to check the code:
* Flush added to print. Avoid potential terminal progress stop.
* Update debugger firmware no longer by default (updated docs as well)
* Add hint during openocd error about potential debugger firmware update required.

Install script refine

---

tools/psoc6/mpy-psoc6.py

* Adding kitprog serial adapter serial number option to be able to setup/erase a specific PSoC6 device when multiples devices are connected to the machine.

tools/psoc6/mpy-psoc6.py: Added serial adapter serial num opt.

---

README.md

* Updated links to point to psoc6 fork related links.
* Updated badges

README.md: Links update for psoc6 fork.

---

tests/ports/psoc6/run_psoc6_tests.sh

Updated our psoc6 tests to changes in cli of tests/run-tests.py

tests/ports/psoc6/run_psoc6_tests.sh: Upgraded run-tests.py.

---

docs/psoc6/quickref.rst

Fix level in doc. Minor change.

docs/psoc6/quickref.rst: Fix levels.

---

examples/usercimaimodule/imagimob/README.md
examples/usercimaimodule/imagimob/imai_mp_iface.c
ports/psoc6/Makefile
ports/psoc6/README.md

- Docs updated with links and additional setup details.
- Minor changes in Makefile and interface as per user feedback.

examples/usercimaimodule/imagimob: Update doc and mior fix in Makefile.

---

ports/psoc6/Makefile
tools/ci.sh
tools/metrics.py

Fake PR to check if code-size gets triggered correctly.

tools/ci.sh: Generate dup changes.

---

examples/natmod/deepcraft/Makefile

Makefile changes for windows operation.

examples/natmod/deepcraft: Refactor makefile to allow exec in windows.

---

docs/psoc6/quickref.rst

Fixed SPI pin number for master in docs.

docs/psoc6/quickref: Fix SPI master pins.

---

tests/ports/psoc6/run_psoc6_tests.sh

* I added twice the time_pulse... 😓 Now removed.
* But now I have added the fail fast by default.

tests/ports/psoc6/run_psoc6_tests: Added fail fast by default.
